# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setFixedSize(QSize(266, 202))
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 266, 270))
        self.widget.setObjectName("widget")
        self.name = QtWidgets.QLabel(self.widget)
        self.name.setGeometry(QtCore.QRect(0, 0, 266, 81))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(25)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.all_time = QtWidgets.QLabel(self.widget)
        self.all_time.setGeometry(QtCore.QRect(0, 110, 266, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.all_time.setFont(font)
        self.all_time.setObjectName("all_time")
        self.active_time = QtWidgets.QLabel(self.widget)
        self.active_time.setGeometry(QtCore.QRect(0, 140, 266, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.active_time.setFont(font)
        self.active_time.setObjectName("active_time")
        self.active_or_not = QtWidgets.QLabel(self.widget)
        self.active_or_not.setGeometry(QtCore.QRect(0, 170, 266, 16))
        self.active_or_not.setAutoFillBackground(False)
        self.active_or_not.setStyleSheet("")
        self.active_or_not.setText("")
        self.active_or_not.setObjectName("active_or_not")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.name.setText(_translate("Form", "Name"))
        self.all_time.setText(_translate("Form", "All Time"))
        self.active_time.setText(_translate("Form", "Active Time"))
